version: '3.8'

services:
  postgres:
    image: postgres:latest
    build: ./db
    env_file:
      - .env
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    depends_on:
      - postgres
    environment:
      CUDA_LAUNCH_BLOCKING: 1
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: "postgres"
      DB_PORT: 5432
      BACK_PORT: ${BACK_PORT}
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
      HUGCHAT_LOGIN: ${HUGCHAT_LOGIN}
      HUGCHAT_PASS: ${HUGCHAT_PASS}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    networks:
      - mynetwork
    volumes:
      - data-volume:/app/data
      - chroma_data:/app/chroma


  streamlit:
    build:
      context: ../
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "8501:8501"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: "postgres"
      DB_PORT: 5432
      BACK_PORT: ${BACK_PORT}
    depends_on:
      - fastapi
    networks:
      - mynetwork
    volumes:
      - data-volume:/app/data

  minio:
      image: minio/minio
      container_name: minio
      environment:
        MINIO_ROOT_USER: ${MINIO_ROOT_USER}     # Установите значения в файле .env
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}  # Установите значения в файле .env
      ports:
        - "9190:9000"  # Порт для доступа к S3 API
        - "9191:9191"  # Порт для доступа к MinIO Console
      volumes:
        - minio_data:/data
      command: server /data --console-address ":9191"
      networks:
        - mynetwork

volumes:
  postgres_data:
  data-volume:
  minio_data:
  chroma_data:


networks:
  mynetwork:
    driver: bridge